export const GET_INCIDENT = 'GET_INCIDENT';
export const GET_INCIDENTS = 'GET_INCIDENTS';
export const GET_INCIDENT_LOCATION = 'GET_INCIDENT_LOCATION';
export const INCIDENT_LOADING = 'INCIDENT_LOADING';
export const INCIDENT_LOCATION_LOADING = 'INCIDENT_LOCATION_LOADING';
export const INCIDENT_NOT_FOUND = 'INCIDENT_NOT_FOUND';

