language: node_js
dist: trusty
node_js:
  - "8.9.1"
sudo: true
git:
  depth: 1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn cache clean
  - yarn
branches:
  only:
    - develop
jobs:
  include:
    - stage: test
      script:
        - yarn test
      after_success:
        - yarn coveralls
    - stage: build
      script:
        - yarn build
