export enum ActionType {
  INCIDENT_REQUEST = 'INCIDENT_REQUEST',
  INCIDENT_REQUEST_SUCCESS = 'INCIDENT_REQUEST_SUCCESS',

  INCIDENTS_REQUEST = 'INCIDENTS_REQUEST',
  INCIDENTS_REQUEST_SUCCESS = 'INCIDENTS_REQUEST_SUCCESS',
  INCIDENTS_REQUEST_FAILURE = 'INCIDENTS_REQUEST_FAILURE',

  INCIDENT_POSITION_REQUEST = 'INCIDENT_POSITION_REQUEST',
  INCIDENT_POSITION_REQUEST_SUCCESS = 'INCIDENT_POSITION_REQUEST_SUCCESS'
}
