export enum ActionType {
  INCIDENT_REQUEST = 'INCIDENT_REQUEST',
  INCIDENT_RECEIVE = 'INCIDENT_RECEIVE',

  INCIDENTS_REQUEST = 'INCIDENTS_REQUEST',
  INCIDENTS_RECEIVE = 'INCIDENTS_RECEIVE',

  INCIDENT_POSITION_REQUEST = 'INCIDENT_POSITION_REQUEST',
  INCIDENT_POSITION_RECEIVE = 'INCIDENT_POSITION_RECEIVE'
}
