export const ListActionTypes = {
    FETCH_LIST: 'FETCH_LIST',
    FETCH_LIST_PAGINATION: 'FETCH_LIST_PAGINATION',
    FETCH_SINGLE_INCIDENT: 'FETCH_SINGLE_INCIDENT',
    FETCH_SINGLE_INCIDENT_MAP: 'FETCH_SINGLE_INCIDENT_MAP',
    RESET_DETAIL_STATE: 'RESET_DETAIL_STATE',
    RESET_LIST_STATE: 'RESET_LIST_STATE',

}