export const FETCHING_LIST = 'FETCHING_LIST';
export const FETCHED_LIST = 'FETCHED_LIST';
export const ERROR_FETCHING_LIST = 'ERROR_FETCHING_LIST';
export const FETCH_CASE_DETAILS = 'FETCH_CASE_DETAILS';
