export const DATA_GET = 'DATA_GET';
export const DATA_GET_ERROR = 'DATA_GET_ERROR';
export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS';
export const DATA_RESET_ERROR = 'DATA_RESET_ERROR';
export const DATA_PAGE_NUMBER_CHANGE = 'DATA_PAGE_NUMBER_CHANGE';
